#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata":{"name":"kyverno-background-controller"}})
---
spec:
  #@overlay/match missing_ok=True
  replicas: #@ data.values.background_controller.replicas

#@ if/end data.values.background_controller.replicas > 1:
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kyverno-background-controller-pdb
  namespace: kyverno
  labels:
    app.kubernetes.io/component: background-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/part-of: kyverno
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/component: background-controller
      app.kubernetes.io/instance: kyverno
      app.kubernetes.io/part-of: kyverno
